version: "3.7"

services:
  springboot-hello-world:
    container_name: "springboot-hello-world"
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: "unless-stopped"
